### ISSUE TITLE
Posts Tik Tok Embeds But No Videos

### ISSUE THREAD

**Issue by MrSaxon** [adryd325/discord-twitter-video-embeds#16]
For a short time, the bot was posting embeds and videos whenever someone linked to Tik Tok, which was great, but now we no longer get the videos. The bot just posts the embeds and nothing else. Is it possible to fix it so that the videos are posted again, or stop it from posting the embedded descriptions? I'd prefer it post nothing at all if it's not going to post the videos.

**Comment by adryd325** [comment]
i must've got ip banned from tiktok again. im away right now but i'll try to fix it on tuesday or wednesday when i'm home
