### ISSUE TITLE
Recompose

### ISSUE THREAD

**Issue by dobbleg1000** [adryd325/discord-twitter-video-embeds#28]
Is it possible to have recompose not break the profile of the poster
![image](https://github.com/adryd325/discord-twitter-video-embeds/assets/11370810/2705923a-de47-497a-b872-b59f42b7c8da)
This makes it difficult to search history for a user.

**Comment by dobbleg1000** [comment]
![image](https://github.com/adryd325/discord-twitter-video-embeds/assets/11370810/cd81cc84-2097-46bb-9ca7-8435ef89bcc7)

**Comment by adryd325** [comment]
This is a limitation with Discord. We use a trick that with webhooks that sets the name and profile picture of the webhook to that of the sender.
