### ISSUE TITLE
Discord fixed Twitter videos, add an option to disable Twitter

### ISSUE THREAD

**Issue by adryd325** [adryd325/discord-twitter-video-embeds#3]
The bot is still useful for twitter since videos don't embed on mobile. But some may find the bot annoying

**Comment by sheikchick** [comment]
This would be nice

**Comment by Nikoskio2** [comment]
Same would also be helpful for reddit posts :)

**Comment by adryd325** [comment]
This probably won't come any time soon as I'm busy with college and this would likely require adding some more columns to the database for guilds.

**Comment by adryd325** [comment]
As of now I don't think this is worth implementing, perhaps in the future I'll revisit this; especially if I implement #13 since I want for it to be opt-in
